# Generated by Django 2.1.2 on 2019-01-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='credit',
            field=models.PositiveSmallIntegerField(default=0, help_text='Amount of credit/token user have'),
        ),
    ]
