# Generated by Django 2.1.2 on 2019-01-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total amount of screenshot till now'),
        ),
    ]
