# Generated by Django 2.1.2 on 2019-01-10 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequestmodel',
            name='req_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
